MwPackage(
    "/metawrap/javascript/lib/",
    "com.metawrap.stateviewengine",
    [
		"MetaWrap.Cookie",
    	"MetaWrap.Pipeline",
    	"MetaWrap.Network",
    	"MetaWrap.XML",
    	"MetaWrap.XML.Serialise",
		"MetaWrap.XML.Action",
    	"MetaWrap.Page",
    	"MetaWrap.Page.Output",
    	"MetaWrap.XML.XSLT",
        "MetaWrap.CSS",        
        "MetaWrap.View",
        "MetaWrap.StateViewMap",
        "MetaWrap.State"
    ]
    );
